tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
brew "autoconf"
brew "automake"
brew "coreutils"
brew "unbound"
brew "gnutls"
brew "libksba"
brew "readline"
brew "gnupg"
brew "libtool"
brew "pkg-config"
brew "libyaml"
brew "postgresql@14", restart_service: true
brew "zlib"
